services:
  - type: web
    name: dmnlight-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn API.rest.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TERMINUS_URL
        value: ""
      - key: PYTHON_VERSION
        value: "3.11.0"
